### ISSUE TITLE
No need to convert OmegaConf to json.

### ISSUE THREAD

**Issue by omry** [withsmilo/When-ML-pipeline-meets-Hydra#2]
https://github.com/withsmilo/When-ML-pipeline-meets-Hydra/blob/c88cf432dd6bcc71fc2638fab89e35eb57a864f5/src/when_ml_pipeline_meets_hydra/api/modeling.py#L6

Try to stick to OmegaConf. there are big advantages for it over straight json.
Take a look at the docs here:
https://omegaconf.readthedocs.io/en/latest/usage.html

**Comment by withsmilo** [comment]
@omry :
Thank you so much for letting me know that I didn't know. I'm not familiar with OmegaConf yet. I fixed my codes. :smiley:
